redmine-plugins/redmine_agile/config/routes.rb
# This file is a part of Redmin Agile (redmine_agile) plugin,
# Agile board plugin for redmine
#
# Copyright (C) 2011-2020 RedmineUP
# http://www.redmineup.com/
#
# redmine_agile is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# redmine_agile is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with redmine_agile.  If not, see <http://www.gnu.org/licenses/>.

# Plugin's routes
# See: http://guides.rubyonrails.org/routing.html

resources :projects do
  resources :agile_queries, only: [:new, :create]
end

resources :issues do
  get "done_ratio", :to => "agile_journal_details#done_ratio"
  get "status", :to => "agile_journal_details#status"
  get "assignee", :to => "agile_journal_details#assignee"
  member do
    get "agile_data", :to => "agile_boards#agile_data"
  end
end

resources :agile_queries

get '/projects/:project_id/agile/charts', :to => "agile_charts#show", :as => "project_agile_charts"
get '/agile/charts/', :to => "agile_charts#show", :as => "agile_charts"
get '/agile/charts/render_chart', :to => "agile_charts#render_chart"
get '/agile/charts/select_version_chart', :to => "agile_charts#select_version_chart"
get '/projects/:project_id/agile/board', :to => 'agile_boards#index'
get '/agile/board', :to => 'agile_boards#index'
put '/agile/board', :to => 'agile_boards#update', :as => 'update_agile_board'
get '/agile/issue_tooltip', :to => 'agile_boards#issue_tooltip', :as => 'issue_tooltip'
get '/agile/inline_comment', :to => 'agile_boards#inline_comment', :as => 'agile_inline_comment'
post 'projects/:project_id/agile/create_issue', :to => 'agile_boards#create_issue', :as => 'agile_create_issue'

redmine-plugins/redmine_agile/app/controllers/agile_boards_controller.rb
# This file is a part of Redmin Agile (redmine_agile) plugin,
# Agile board plugin for redmine
#
# Copyright (C) 2011-2020 RedmineUP
# http://www.redmineup.com/
#
# redmine_agile is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# redmine_agile is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with redmine_agile.  If not, see <http://www.gnu.org/licenses/>.

class AgileBoardsController < ApplicationController
  unloadable

  menu_item :agile

  before_action :find_issue, only: [:update, :issue_tooltip, :inline_comment, :edit_issue, :update_issue, :agile_data]
  before_action :find_optional_project, only: [:index, :create_issue]
  before_action :authorize, except: [:index, :edit_issue, :update_issue]

  accept_api_auth :agile_data

  helper :issues
  helper :journals
  helper :projects
  include ProjectsHelper
  helper :custom_fields
  include CustomFieldsHelper
  helper :issue_relations
  include IssueRelationsHelper
  helper :watchers
  include WatchersHelper
  helper :attachments
  include AttachmentsHelper
  helper :queries
  include QueriesHelper
  helper :repositories
  include RepositoriesHelper
  helper :sort
  include SortHelper
  include IssuesHelper
  helper :timelog
  include RedmineAgile::AgileHelper
  helper :checklists if RedmineAgile.use_checklist?

  def index
    retrieve_agile_query
    if @query.valid?
      @issues = @query.issues
      @issue_board = @query.issue_board
      @board_columns = @query.board_statuses

      respond_to do |format|
        format.html { render :template => 'agile_boards/index', :layout => !request.xhr? }
        format.js
      end
    else
      respond_to do |format|
        format.html { render(:template => 'agile_boards/index', :layout => !request.xhr?) }
        format.js
      end
    end
  rescue ActiveRecord::RecordNotFound
    render_404
  end

  def update
    (render_403; return false) unless @issue.editable?
    retrieve_agile_query_from_session
    old_status = @issue.status
    @issue.init_journal(User.current)
    @issue.safe_attributes = auto_assign_on_move? ? params[:issue].merge(:assigned_to_id => User.current.id) : params[:issue]
    checking_params = params.respond_to?(:to_unsafe_hash) ? params.to_unsafe_hash : params

    saved = checking_params['issue'] && checking_params['issue'].inject(true) do |total, attribute|
      if @issue.attributes.include?(attribute.first)
        total &&= @issue.attributes[attribute.first].to_i == attribute.last.to_i
      else
        total &&= true
      end
    end
    call_hook(:controller_agile_boards_update_before_save, { params: params, issue: @issue})
    @update = true
    if saved && @issue.save
      call_hook(:controller_agile_boards_update_after_save, { :params => params, :issue => @issue})
      AgileData.transaction do
        Issue.eager_load(:agile_data).find(params[:positions].keys).each do |issue|
          issue.agile_data.position = params[:positions][issue.id.to_s]['position']
          issue.agile_data.save
        end
      end if params[:positions]

      @inline_adding = params[:issue][:notes] || nil

      respond_to do |format|
        format.html { render(:partial => 'issue_card', :locals => {:issue => @issue}, :status => :ok, :layout => nil) }
      end
    else
      respond_to do |format|
        messages = @issue.errors.full_messages
        messages = [l(:text_agile_move_not_possible)] if messages.empty?
        format.html {
          render json: messages, status: :unprocessable_entity, layout: nil
        }
      end
    end
  end

  def issue_tooltip
    render :partial => 'issue_tooltip'
  end

  def inline_comment
    render 'inline_comment', :layout => nil
  end

  def agile_data
    @agile_data = @issue.agile_data
    return render_404 unless @agile_data

    respond_to do |format|
      format.any { head :ok }
      format.api { }
    end
  end

  private

  def auto_assign_on_move?
    RedmineAgile.auto_assign_on_move? && @issue.assigned_to.nil? &&
      !params[:issue].keys.include?('assigned_to_id') &&
      @issue.status_id != params[:issue]['status_id'].to_i
  end
end

redmine-plugins/redmine_agile/app/helpers/agile_boards_helper.rb
# encoding: utf-8
#
# This file is a part of Redmin Agile (redmine_agile) plugin,
# Agile board plugin for redmine
#
# Copyright (C) 2011-2020 RedmineUP
# http://www.redmineup.com/
#
# redmine_agile is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# redmine_agile is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with redmine_agile.  If not, see <http://www.gnu.org/licenses/>.

module AgileBoardsHelper
  def agile_color_class(issue, options={})
    ''
      end

  def agile_user_color(user, options={})
  end

  def header_th(name, rowspan = 1, colspan = 1, leaf = nil)
    th_attributes = {}
    if leaf
      # th_attributes[:style] = ""
      th_attributes[:"data-column-id"] = leaf.id
      issue_count = leaf.instance_variable_get("@issue_count") || 0
      count_tag = " (#{content_tag(:span, issue_count.to_i, :class => 'count')})".html_safe
      

      # estimated hours total
      story_points_count = leaf.instance_variable_get("@story_points") || 0
      hours_count = leaf.instance_variable_get("@estimated_hours_sum") || 0
      values = []
      values << '%.2fh' % hours_count.to_f if hours_count > 0
      values << "#{story_points_count}sp" if story_points_count > 0
      if values.present?
        hours_tag = content_tag(:span, values.join('/').html_safe, class: 'hours', title: l(:field_estimated_hours))
      end
    end
    content_tag :th, h(name) + count_tag + hours_tag, th_attributes
  end

  def render_board_headers(columns)
    "<tr>#{columns.map{|column| header_th(column.name, 1, 1, column)}.join}</tr>".html_safe
      end

  def color_by_name(name)
    "##{"%06x" % (name.unpack('H*').first.hex % 0xffffff)}"
  end

  def render_board_fields_selection(query)
    query.available_inline_columns.reject(&:frozen?).reject{ |c| c.name == :story_points && !RedmineAgile.use_story_points? }.map do |column|
      label_tag('', check_box_tag('c[]', column.name, query.columns.include?(column)) + column.caption, :class => "floating" )
    end.join(" ").html_safe
  end

  def render_board_fields_status(query)
    available_statuses = Redmine::VERSION.to_s >= '3.4' && @project ? @project.rolled_up_statuses : IssueStatus.sorted
    current_statuses = query.options[:f_status] || IssueStatus.where(:is_closed => false).pluck(:id).map(&:to_s)
    wp = query.options[:wp] || {}
    status_tags = available_statuses.map do |status|
      label_tag('', check_box_tag('f_status[]', status.id, current_statuses.include?(status.id.to_s)
      ) + status.to_s, :class => 'floating')
    end.join(' ').html_safe
    hidden_field_tag('f[]', 'status_id').html_safe +
      hidden_field_tag('op[status_id]', "=").html_safe +
      status_tags
  end

  def render_issue_card_hours(query, issue)
    hours = []
    hours << "%.2f" % issue.total_spent_hours.to_f if query.has_column_name?(:spent_hours) && issue.total_spent_hours > 0
    hours << "%.2f" % issue.estimated_hours.to_f if query.has_column_name?(:estimated_hours) && issue.estimated_hours
    hours = [hours.join('/') + "h"] unless hours.blank?
    hours << "#{issue.story_points}sp" if RedmineAgile.use_story_points? && query.has_column_name?(:story_points) && issue.story_points

    content_tag(:span, "(#{hours.join('/')})", :class => 'hours') unless hours.blank?
  end

  def agile_progress_bar(pcts, options={})
    pcts = [pcts, pcts] unless pcts.is_a?(Array)
    pcts = pcts.collect(&:round)
    pcts[1] = pcts[1] - pcts[0]
    pcts << (100 - pcts[1] - pcts[0])
    width = options[:width] || '100px;'
    legend = options[:legend] || ''
    content_tag('table',
      content_tag('tr',
        (pcts[0] > 0 ? content_tag('td', '', :style => "width: #{pcts[0]}%;", :class => 'closed') : ''.html_safe) +
        (pcts[1] > 0 ? content_tag('td', '', :style => "width: #{pcts[1]}%;", :class => 'done') : ''.html_safe) +
        (pcts[2] > 0 ? content_tag('td', '', :style => "width: #{pcts[2]}%;", :class => 'todo') : ''.html_safe) +
        (legend ? content_tag('td', content_tag('p', legend, :class => 'percent'), :class => 'legend') : ''.html_safe)
      ), :class => "progress progress-#{pcts[0]}", :style => "width: #{width};").html_safe
  end

  def issue_children(issue)
    return unless issue.children.any?
    content_tag :ul do
      issue.children.select{ |x| x.visible? }.each do |child|
        id = if @query.has_column_name?(:tracker) || @query.has_column_name?(:id) then "##{child.id}:&nbsp;" else '' end
        concat "<li class='#{'task-closed' if child.closed?}'><a href='#{issue_path(child)}'>#{id}#{child.subject}</a></li>#{issue_children(child)}".html_safe
      end
    end
  end

  def time_in_state(distance=nil)
    return "" if !distance || !(distance.is_a? Time)
    distance = Time.now - distance
    hours = distance/(3600)
    return "#{I18n.t('datetime.distance_in_words.x_hours', :count => hours.to_i)}" if hours < 24
    "#{I18n.t('datetime.distance_in_words.x_days', :count => (hours/24).to_i)}"
  end

  def class_for_closed_issue(issue, is_version_board)
    return '' if !RedmineAgile.hide_closed_issues_data? && !is_version_board
    return 'closed-issue' if issue.closed?
    ''
  end

  def init_agile_tooltip_info(options={})
    js_code = "function callGetToolTipInfo()
      {
        var url = '#{issue_tooltip_url}';
        agileBoard.getToolTipInfo(this, url);
      }
      $('.tooltip').mouseenter(callGetToolTipInfo);
    "
    return js_code.html_safe if options[:only_code]
    javascript_tag(js_code)
  end

  def estimated_value(issue)
    return (issue.story_points || 0) if RedmineAgile.use_story_points?
    issue.estimated_hours.to_f || 0
  end

  def estimated_time_value(query, issue)
    issue.estimated_hours.to_f if query.has_column_name?(:estimated_hours)
  end

  def story_points_value(query, issue)
    issue.story_points.to_f if query.has_column_name?(:story_points) && RedmineAgile.use_story_points?
  end

  def show_checklist?(issue)
    RedmineAgile.use_checklist? && issue.checklists.any? && User.current.allowed_to?(:view_checklists, issue.project)
  rescue
    false
  end
end

redmine-plugins/redmine_agile/app/views/agile_boards/_backlog_column.html.erb
<td class="issue-backlog-col" rowspan="<%= rowspan %>">
  <div class="issue-backlog-search">
    <%= text_field_tag('search', '', placeholder: l(:label_agile_board_search_backlog_issues)) %>
    <%= javascript_tag("observeIssueSearchfield('search', '#{backlog_autocomplete_agile_boards_path(project_id: query.project.try(:id))}');") %>
  </div>
  <div class="backlog-issues issue-status-col <%= 'empty' if @backlog_issues.empty? %>" data-id="">
    <% paginator = query.issues_paginator(@backlog_issues, params[:page]) %>
    <%= render partial: 'issues_list', locals: { column_id: nil,
                                                 project: query.project,
                                                 issues: @backlog_issues.offset(paginator.offset).limit(paginator.per_page).all,
                                                 more_url: backlog_load_more_agile_boards_path(project_id: query.project.try(:id),
                                                                                               q: params[:q],
                                                                                               page: paginator.next_page) } %>
  </div>
</td>

redmine-plugins/redmine_agile/app/views/agile_boards/_issue_card.html.erb
<div class="issue-card hascontextmenu <%= agile_color_class(issue, :color_base => @query.respond_to?(:color_base) && @query.color_base) %> <%= class_for_closed_issue(issue, @version_board) %>"
     data-id="<%= issue.id %>"
     data-estimated-hours="<%= estimated_time_value(@query, issue).to_f %>"
     data-story-points="<%= story_points_value(@query, issue).to_f %>"
     style="<%= agile_user_color(issue.assigned_to, :color_base => @query.respond_to?(:color_base) && @query.color_base) if issue.assigned_to %>">

  <% if issue.closed? && RedmineAgile.hide_closed_issues_data? && !@version_board %>
      <span class="fields">
         <div class="tooltip">
           <p class="issue-id <%= 'without-tracker' if @query.has_column_name?(:tracker).blank? %>">
               <strong><%= link_to "#{'#' + issue.id.to_s}", issue_path(issue) %></strong>
            </p>
            <span class="tip">
            </span>
          </div>
      </span>
    <% else %>
      <span class="fields">
          <% if User.current.allowed_to?(:edit_issues, @project, :global => true) && !@version_board %>
            <div class="quick-edit-card">
              <%= link_to image_tag("/images/comment.png", alt: 'Comment'), '#', onclick: "showInlineComment(this, '#{j(agile_inline_comment_path(:id => issue))}'); return false;", title: l(:label_comment_add), class: 'add-comment' if RedmineAgile.allow_inline_comments? %>
            </div>
          <% end %>
          <% if @query.has_column_name?(:project) %>
            <p class="project">
              <%= issue.project.name %>
            </p>
          <% end %>
          <p class="issue-id <%= 'without-tracker' if @query.has_column_name?(:tracker).blank? %>">
            <%= check_box_tag("ids[]", issue.id, false, :id => nil, :class => 'checkbox') %>
            <% if @query.has_column_name?(:tracker) %>
              <strong><%= issue_heading(issue) %></strong>
            <% end %>
            <%= render_issue_card_hours(@query, issue) %>
          </p>
          <p class="name" ><%= link_to "#{'#' + issue.id.to_s + ': ' if @query.has_column_name?(:id) && @query.has_column_name?(:tracker).blank?}#{issue.subject.truncate(100)}", issue_path(issue) %></p>
          <p class="attributes">
            <% @query.card_columns.select{|c| !c.value(issue).blank? }.each do |column| %>
              <b><%= column.caption %></b>: <%= column_content(column, issue) %> <br>
            <% end %>
          </p>

          <% if @query.has_column_name?(:day_in_state) %>
            <p class="attributes">
                <b><%= " #{I18n.t('label_agile_day_in_state')}: " %></b>
                <% find_change_state = false %>
                <% if @query.journals_for_state %>
                  <% @query.journals_for_state.each do |journal| %>
                    <% if journal.journalized_id == issue.id %>
                      <%= time_in_state(journal.created_on) %>
                      <% find_change_state = true %>
                      <% break %>
                    <% end %>
                  <% end %>
                <% end %>

                <% if !find_change_state %>
                  <%= time_in_state(issue.day_in_state) %>
                <% end %>
            </p>
          <% end %>

          <% if @query.has_column_name?(:description) && !issue.description.blank? %>
            <em class="info description">
              <%= issue.description.truncate(200) %>
            </em>
          <% end %>
          <% if @query.has_column_name?(:sub_issues) && issue.sub_issues.any? %>
            <div class='sub-issues'>
              <%= issue_children(issue) %>
            </div>
          <% end %>
          <% if @query.has_column_name?(:thumbnails)  %>
            <% image = issue.attachments.select(&:thumbnailable?).last %>
            <% if image %>
            <div class="thumbnail" style="background-image: url('<%= thumbnail_path(image, :size => 250) %>')">
            </div>
            <% end %>
          <% end %>
          <!-- Check list -->
          <% if @query.has_column_name?(:checklists) && show_checklist?(issue) %>
            <div class="checklist" id="checklist_<%= issue.id %>">
              <ul id="checklist_items">
                <% issue.checklists.each do |checklist_item| %>
                  <%= render :partial => 'checklists/checklist_item', :object => checklist_item %>
                <% end %>
              </ul>
              <script type="text/javascript">
                $("#checklist_<%= issue.id %>").checklist();
              </script>
            </div>
          <% end %>
          <% if @query.has_column_name?(:assigned_to) %>
            <p class="info assigned-user" style="<%= 'display: none;' unless issue.assigned_to %>">
              <span class="user"><%= avatar(issue.assigned_to, :size => "14").to_s.html_safe + " " + link_to_user(issue.assigned_to) if issue.assigned_to %></span>
            </p>
          <% end %>

          <% if @query.has_column_name?(:done_ratio) %>
            <%= progress_bar(issue.done_ratio, :width => '100%') %>
          <% end %>

          <% if (last_comment = @query.issue_last_comment(issue, :inline_adding => @inline_adding)) %>
            <em class="info description last_comment" title='<%= last_comment.user.to_s + " " + format_date(last_comment.created_on) %>'>
              <span class="icon icon-comment last-comment">
                <%= last_comment.notes.truncate(100) %>
              </span>
            </em>
          <% end %>
          <% if User.current.allowed_to?(:edit_issues, @project, :global => true) && RedmineAgile.allow_inline_comments? %>
            <div class="quick-comment">
            </div>
          <% end %>
      </span>
    <% end %>
</div>
<% if User.current.allowed_to?(:edit_issues, @project, :global => true) && @update %>
  <script type="text/javascript">

    document.onkeydown = function(evt) {
        evt = evt || window.event;
        if (evt.keyCode == 27) {
            $('html.agile-board-fullscreen').removeClass('agile-board-fullscreen');
            $(".issue-card").addClass("hascontextmenu");
            saveFullScreenState();
        }
    };

    $("table.issues-board thead").html("<%=escape_javascript render_board_headers(@query.board_statuses) %>");
  </script>

  <% if @error_msg %>
    <script type="text/javascript">
      setErrorMessage("<%= @error_msg%>", 'warning');
    </script>
  <% end %>

  <% if @update && !@version_board %>
    <script type="text/javascript">
      $("table.issues-board thead").html("<%=escape_javascript render_board_headers(@query.board_statuses) %>");
    </script>
    <% if Redmine::VERSION.to_s > '2.4' %>
      <script type="text/javascript">
        agileBoard.initDroppable();
      </script>
    <% end %>
  <% end %>
  <%= init_agile_tooltip_info %>
<% end %>

redmine-plugins/redmine_agile/app/views/agile_boards/_issue_tooltip.html.erb
<%= render_issue_tooltip @issue %>

redmine-plugins/redmine_agile/app/views/agile_boards/_issues_links.html.erb
<h3><%= l(:label_issue_plural) %></h3>

<ul>
  <li><%= link_to l(:label_issue_view_all), _project_issues_path(@project, :set_filter => 1) %></li>
  <% if @project %>
    <li><%= link_to l(:field_summary), project_issues_report_path(@project) %></li>
  <% end %>
  <% if User.current.allowed_to?(:view_calendar, @project, :global => true) %>
    <li><%= link_to l(:label_calendar), _project_calendar_path(@project) %></li>
  <% end %>
  <% if User.current.allowed_to?(:view_gantt, @project, :global => true) %>
    <li><%= link_to l(:label_gantt), _project_gantt_path(@project) %></li>
  <% end %>
  <% if User.current.allowed_to?(:view_agile_queries, @project) %>
    <li><%= link_to l(:label_agile_board), {:controller => "agile_boards", :action => "index", :project_id => @project} %></li>
  <% end %>
</ul>

redmine-plugins/redmine_agile/app/views/agile_boards/_members.html.erb
<div class="project-members">
  <h3><%=l(:label_member_plural)%></h3>
    <% @project.assignable_users.each do |user| %>
      <span class="assignable-user" data-id="<%= user.id %>"><%= avatar(user.is_a?(User) ? user : '<gravatar>', :size => "14", :style => agile_user_color(user, :color_base => @query.respond_to?(:color_base) && @query.color_base) ).to_s.html_safe + " " + link_to_user(user) %>
      <br>
      </span>
    <% end %>
</div>

redmine-plugins/redmine_agile/app/views/agile_boards/_upgrade_to_pro.html.erb
<h3><%= l(:label_agile_light_free_version) %></h3>
<ul>
  <li><%= link_to l(:label_agile_link_to_pro), "https://www.redmineup.com/pages/plugins/agile#pricing?from=light_upgrade" %>
	</li>
	<li><%= link_to l(:label_agile_link_to_pro_demo), "http://demo.redmineup.com/projects/agile/agile/board?query_id=4?from=light_live_preview" %>
	</li>
	<li><%= link_to l(:label_agile_link_to_more_plugins), "https://www.redmineup.com/pages/plugins?from=light_more_plugins" %>
	</li>
</ul>

redmine-plugins/redmine_agile/app/views/agile_boards/autocomplete.js.erb
$(".issues-board div[data-id='<%= @column_id %>']").html('<%= escape_javascript(render partial: "issues_list", locals: { project: @project, issues: @issues, more_url: @more_url }) %>')

redmine-plugins/redmine_agile/app/views/agile_boards/index.html.erb
<%= render 'index' %>
<%= init_agile_tooltip_info %>
<%= call_hook(:view_agile_board_bottom, { :issues => @issues, :project => @project, :query => @query }) %>

redmine-plugins/redmine_agile/app/views/agile_boards/index.js.erb
$('#content').html('<%= j(render('index')) %>')
$('table.issues-board').StickyHeader();
<%= init_agile_tooltip_info(:only_code => true) %>

redmine-plugins/redmine_agile/app/views/agile_boards/inline_comment.html.erb
<%= text_area_tag "issue[notes]", "", :cols => 60, :rows => 5, :class => 'wiki-edit', :no_label => true %>
<button type="button" onclick="saveInlineComment(this, '<%= update_agile_board_path(:id => @issue) %>'); return false;">  <%= l(:button_submit) %> </button>
<%= link_to l(:button_cancel), "#", :onclick => "cancelInlineComment(this);return false;" %>

redmine-plugins/redmine_agile/app/views/agile_boards/load_more.js.erb
$(".issues-board div[data-id='<%= @column_id %>'] .load-more").replaceWith('<%= escape_javascript(render partial: "issues_list", locals: { project: @project, issues: @issues, more_url: @more_url }) %>')

redmine-plugins/redmine_agile/app/views/agile_boards/update.js.erb
decHtmlNumber('th[data-column-id="<%= params[:old_status_id] %>"] span.count');
incHtmlNumber('th[data-column-id="<%= params[:new_status_id] %>"] span.count');
decHtmlNumber('tr.group.swimlane[data-id="<%= params[:old_swimlane_id] %>"] td span.count');
incHtmlNumber('tr.group.swimlane[data-id="<%= params[:new_swimlane_id] %>"] td span.count');

//$('.issue-card[data-id="<%= @issue.id %>"]').html("<%= render :partial => 'issue_card', :locals => {:issue => @issue} %>");