redmine-plugins/redmine_agile/config/routes.rb
# This file is a part of Redmin Agile (redmine_agile) plugin,
# Agile board plugin for redmine
#
# Copyright (C) 2011-2020 RedmineUP
# http://www.redmineup.com/
#
# redmine_agile is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# redmine_agile is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with redmine_agile.  If not, see <http://www.gnu.org/licenses/>.

# Plugin's routes
# See: http://guides.rubyonrails.org/routing.html

resources :projects do
  resources :agile_queries, only: [:new, :create]
end

resources :issues do
  get "done_ratio", :to => "agile_journal_details#done_ratio"
  get "status", :to => "agile_journal_details#status"
  get "assignee", :to => "agile_journal_details#assignee"
  member do
    get "agile_data", :to => "agile_boards#agile_data"
  end
end

resources :agile_queries

get '/projects/:project_id/agile/charts', :to => "agile_charts#show", :as => "project_agile_charts"
get '/agile/charts/', :to => "agile_charts#show", :as => "agile_charts"
get '/agile/charts/render_chart', :to => "agile_charts#render_chart"
get '/agile/charts/select_version_chart', :to => "agile_charts#select_version_chart"
get '/projects/:project_id/agile/board', :to => 'agile_boards#index'
get '/agile/board', :to => 'agile_boards#index'
put '/agile/board', :to => 'agile_boards#update', :as => 'update_agile_board'
get '/agile/issue_tooltip', :to => 'agile_boards#issue_tooltip', :as => 'issue_tooltip'
get '/agile/inline_comment', :to => 'agile_boards#inline_comment', :as => 'agile_inline_comment'
post 'projects/:project_id/agile/create_issue', :to => 'agile_boards#create_issue', :as => 'agile_create_issue'

redmine-plugins/redmine_agile/app/controllers/agile_journal_details_controller.rb
# This file is a part of Redmin Agile (redmine_agile) plugin,
# Agile board plugin for redmine
#
# Copyright (C) 2011-2020 RedmineUP
# http://www.redmineup.com/
#
# redmine_agile is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# redmine_agile is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with redmine_agile.  If not, see <http://www.gnu.org/licenses/>.

class AgileJournalDetailsController < ApplicationController
  unloadable

  before_action :find_issue

  helper :issues
  helper :agile_support
  include AgileSupportHelper

  def done_ratio
    @done_ratios = @issue.journals.map(&:details).flatten.select {|detail| 'done_ratio' == detail.prop_key }.sort_by {|a| a.journal.created_on }
    @done_ratios.unshift(JournalDetail.new(:property => 'attr', :prop_key => 'done_ratio', :value => history_initial_value(@done_ratios) || @issue.done_ratio,
                                           :journal => Journal.new(:user => @issue.author, :created_on => @issue.created_on)))
  end

  def status
    @statuses_collector = AgileStatusesCollector.new(@issue)
    @group = params[:group_by] if params[:group_by].present?

    respond_to do |format|
      format.html
      format.csv  { send_data(issue_statuses_to_csv(@statuses_collector), type: 'text/csv; header=present', filename: "issue_#{@issue.id}_statuses.csv") }
    end
  end

  def assignee
    @assignees = @issue.journals.map(&:details).flatten.select {|detail| 'assigned_to_id' == detail.prop_key }.sort_by {|a| a.journal.created_on }
    @assignees.unshift(JournalDetail.new(:property => 'attr', :prop_key => 'assigned_to_id', :value => history_initial_value(@assignees) || @issue.assigned_to_id,
                                         :journal => Journal.new(:user => @issue.author, :created_on => @issue.created_on)))
  end

  def edit
  end

  def new
  end

  private

  def find_issue
    @issue = Issue.eager_load(:journals => :details).find(params[:issue_id])
    raise Unauthorized unless @issue.visible?
    @project = @issue.project
  rescue ActiveRecord::RecordNotFound
    render_404
  end

  def history_initial_value(journals)
    return nil unless journals.present?
    journals.first.old_value
  end
end

redmine-plugins/redmine_agile/app/views/agile_journal_details/_status_detail.html.erb
<% assignee = Principal.where(:id => data.assigned_to_id).first %>
<tr class="<%= cycle('odd', 'even') %>">
  <td class="index"><%= index + 1 %></td>
  <td class="name"><%= format_time(data.journal.created_on) %></td>
  <td><%= issue_status.name %></td>
  <td><%= distance_of_time_in_words(data.end_time, data.start_time).html_safe %></td>
  <td><%= data.journal.user.name %></td>
  <td><%= assignee.try(:name) %></td>
</tr>

redmine-plugins/redmine_agile/app/views/agile_journal_details/assignee.html.erb
<%= title [issue_heading(@issue) , issue_path(@issue)],  l(:field_assigned_to) %>

<% html_title(l(:field_assigned_to)) %>

<% if @assignees.any? %>
  <table class="list"><thead>
  <tr>
      <th>#</th>
      <th><%= l(:field_created_on) %></th>
      <th><%= l(:field_assigned_to) %></th>
      <th><%= l(:field_duration) %></th>
      <th><%= l(:field_author) %></th>
  </tr></thead>
  <% @assignees.each_with_index do |status, index| %>
  <% assignee = User.where(:id => status.value).first %>
  <tr class="<%= cycle('odd', 'even') %>">
      <td class="index"><%= index + 1 %></td>
      <td class="name"><%= format_time(status.journal.created_on) %></td>
      <td class="name"><%= avatar(assignee, :size => "14").to_s.html_safe + " " + link_to_user(assignee) %></td>
      <td><%= event_duration(status, @assignees[index + 1]) %></td>
      <td><%= link_to_user status.journal.user %></td>
  </tr>
  <% end %>
  </table>
<% else %>
<p class="nodata"><%= l(:label_no_data) %></p>
<% end %>

redmine-plugins/redmine_agile/app/views/agile_journal_details/done_ratio.html.erb
<%= title [issue_heading(@issue) , issue_path(@issue)],  l(:field_done_ratio) %>

<% html_title(l(:field_done_ratio)) %>

<% if @done_ratios.any? %>
  <table class="list"><thead>
  <tr>
      <th>#</th>
      <th><%= l(:field_created_on) %></th>
      <th><%= l(:field_done_ratio) %></th>
      <th><%= l(:label_agile_charts_number_of_hours) %></th>
      <th><%= l(:field_duration) %></th>
      <th><%= l(:field_author) %></th>
  </tr></thead>
  <% @done_ratios.each_with_index do |done_ratio, index| %>
  <tr class="<%= cycle('odd', 'even') %>">
      <td class="index"><%= index + 1 %></td>
      <td class="name"><%= format_time(done_ratio.journal.created_on) %></td>
      <td><%= progress_bar(done_ratio.value.to_f, :width => '80px', :legend => "#{"%.2f" %done_ratio.value.to_f}%") %></td>
      <td><%= "%.2f" % (@issue.estimated_hours.to_f * (100 - done_ratio.value.to_f) / 100.0) %></td>
      <td><%= event_duration(done_ratio, @done_ratios[index + 1]) %></td>
      <td><%= done_ratio.journal.user.name %></td>
  </tr>
  <% end %>
  </table>
<% else %>
<p class="nodata"><%= l(:label_no_data) %></p>
<% end %>

redmine-plugins/redmine_agile/app/views/agile_journal_details/edit.html.erb
<h2>AgileDoneRatioFlowsController#edit</h2>

redmine-plugins/redmine_agile/app/views/agile_journal_details/new.html.erb
<h2>AgileDoneRatioFlowsController#new</h2>

redmine-plugins/redmine_agile/app/views/agile_journal_details/status.html.erb
<%= title [issue_heading(@issue) , issue_path(@issue)],  l(:label_issue_status) %>

<% html_title(l(:label_issue_status_plural)) %>

<%= form_tag({ controller: 'agile_journal_details', action: 'status' }, method: :get, id: 'query_form') do %>
  <div id="query_form_with_buttons" class="hide-when-print">
    <div id="query_form_content">
      <fieldset id="options" class="collapsible collapsed">
        <legend onclick="toggleFieldset(this);" class="icon icon-expended"><%= l(:label_options) %></legend>
        <div style="display: none;">
          <table>
            <tr>
              <td><label for='group_by'><%= l(:field_group_by) %></label></td>
              <td><%= select_tag('group_by', options_for_select([[]] + [[l(:field_status), 'status']], params[:group_by])) %></td>
            </tr>
          </table>
        </div>
      </fieldset>
    </div>
  </div>

  <p class="buttons hide-when-print">
    <%= link_to_function l(:button_apply), 'submit_query_form("query_form")', :class => 'icon icon-checked' %>
    <%= link_to l(:button_clear), { }, :class => 'icon icon-reload'  %>
  </p>
<% end %>

<% if @statuses_collector.data.any? %>
  <table class="list"><thead>
  <tr>
      <th>#</th>
      <th><%= l(:field_created_on) %></th>
      <th><%= l(:field_status) %></th>
      <th><%= l(:field_duration) %></th>
      <th><%= l(:field_author) %></th>
      <th><%= l(:field_assigned_to) %></th>
  </tr></thead>
  <% if @group %>
    <% @statuses_collector.grouped_by(@group).each do |group_id, group_data| %>
      <% group_object = @statuses_collector.object_for(@group).where(:id => group_id).first %>
      <tr class="group open">
        <td colspan="6">
          <span class="expander icon icon-expended" onclick="toggleRowGroup(this);">&nbsp;</span>
          <span class="name"><%= group_object.name %></span>
          <span class="badge badge-count count"><%= group_data.count %></span>
          <span class="totals">
            <%= l('datetime.distance_in_words.x_days', count: @statuses_collector.group_total_for(@group, group_data)) %>
          </span>
          <%= link_to_function("#{l(:button_collapse_all)}/#{l(:button_expand_all)}",
                               "toggleAllRowGroups(this)", :class => 'toggle-all') %>
        </td>
      </tr>
      <% group_data.each_with_index do |data, index| %>
        <%= render partial: 'status_detail', locals: { issue_status: @statuses_collector.issue_status_for(@group, group_id), data: data, index: index } %>
      <% end %>
    <% end %>
  <% else %>
    <% @statuses_collector.data.each_with_index do |data, index| %>
      <% issue_status = IssueStatus.where(:id => data.status_id).first %>
      <%= render partial: 'status_detail', locals: { issue_status: issue_status, data: data, index: index } %>
    <% end %>
  <% end %>
  </table>
<% else %>
  <p class="nodata"><%= l(:label_no_data) %></p>
<% end %>

<% other_formats_links do |f| %>
  <%= f.link_to 'CSV', :url => params.respond_to?(:to_unsafe_hash) ? params.to_unsafe_hash : params %>
<% end %>